#############################################################################
# Makefile for building: Device_t
# Generated by qmake (3.1) (Qt 5.9.9)
# Project:  Device_t.pro
# Template: subdirs
# Command: C:/Qt/Qt5.9.9/5.9.9/mingw53_32/bin/qmake.exe -o Makefile Device_t.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:/Qt/Qt5.9.9/5.9.9/mingw53_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = C:/Qt/Qt5.9.9/5.9.9/mingw53_32/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = C:/Qt/Qt5.9.9/5.9.9/mingw53_32/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-MemoryManagement-linked_list_test-linked_list_test-pro \
		sub-MemoryManagement-memory_compression_test-memory_compression_test-pro \
		sub-MemoryManagement-memory_pool_test-memory_pool_test-pro \
		sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro


sub-MemoryManagement-linked_list_test-linked_list_test-pro-qmake_all:  FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd MemoryManagement/linked_list_test/ && $(MAKE) -f Makefile qmake_all
sub-MemoryManagement-linked_list_test-linked_list_test-pro: FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-MemoryManagement-linked_list_test-linked_list_test-pro-make_first: FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-MemoryManagement-linked_list_test-linked_list_test-pro-all: FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-MemoryManagement-linked_list_test-linked_list_test-pro-clean: FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-MemoryManagement-linked_list_test-linked_list_test-pro-distclean: FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-MemoryManagement-linked_list_test-linked_list_test-pro-install_subtargets: FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-MemoryManagement-linked_list_test-linked_list_test-pro-uninstall_subtargets: FORCE
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-qmake_all:  FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd MemoryManagement/memory_compression_test/ && $(MAKE) -f Makefile qmake_all
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro: FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-make_first: FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-all: FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-clean: FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-distclean: FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-install_subtargets: FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-uninstall_subtargets: FORCE
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-qmake_all:  FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd MemoryManagement/memory_pool_test/ && $(MAKE) -f Makefile qmake_all
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro: FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-make_first: FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-all: FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-clean: FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-distclean: FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-install_subtargets: FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-uninstall_subtargets: FORCE
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-qmake_all:  FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd MemoryManagement/ring_buffer_test/ && $(MAKE) -f Makefile qmake_all
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro: FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-make_first: FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-all: FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-clean: FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-distclean: FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-install_subtargets: FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-uninstall_subtargets: FORCE
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall

Makefile: Device_t.pro C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/qdevice.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/sanitize.conf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/gcc-base.conf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/g++-base.conf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/angle.conf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/qconfig.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/toolchain.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/testcase.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/win32/console.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qml_debug.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qmake_use.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/file_copies.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/exceptions.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/lex.prf \
		Device_t.pro
	$(QMAKE) -o Makefile Device_t.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/spec_pre.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/qdevice.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/device_config.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/sanitize.conf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/gcc-base.conf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/g++-base.conf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/common/angle.conf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/qconfig.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_core.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_help.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_location.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_network.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qt_functions.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qt_config.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/win32-g++/qmake.conf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/exclusive_builds.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/toolchain.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/default_pre.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/win32/default_pre.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/resolve_config.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/default_post.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/testcase.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/warn_on.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/win32/console.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qml_debug.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/precompile_header.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/qmake_use.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/file_copies.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/testcase_targets.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/exceptions.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/yacc.prf:
C:/Qt/Qt5.9.9/5.9.9/mingw53_32/mkspecs/features/lex.prf:
Device_t.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Device_t.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: sub-MemoryManagement-linked_list_test-linked_list_test-pro-qmake_all sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-qmake_all sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-qmake_all sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-qmake_all FORCE

make_first: sub-MemoryManagement-linked_list_test-linked_list_test-pro-make_first sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-make_first sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-make_first sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-make_first  FORCE
all: sub-MemoryManagement-linked_list_test-linked_list_test-pro-all sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-all sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-all sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-all  FORCE
clean: sub-MemoryManagement-linked_list_test-linked_list_test-pro-clean sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-clean sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-clean sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-clean  FORCE
distclean: sub-MemoryManagement-linked_list_test-linked_list_test-pro-distclean sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-distclean sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-distclean sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-MemoryManagement-linked_list_test-linked_list_test-pro-install_subtargets sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-install_subtargets sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-install_subtargets sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-install_subtargets FORCE
uninstall_subtargets: sub-MemoryManagement-linked_list_test-linked_list_test-pro-uninstall_subtargets sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-uninstall_subtargets sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-uninstall_subtargets sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-uninstall_subtargets FORCE

sub-MemoryManagement-linked_list_test-linked_list_test-pro-debug:
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-debug:
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-debug:
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-debug:
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
debug: sub-MemoryManagement-linked_list_test-linked_list_test-pro-debug sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-debug sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-debug sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-debug

sub-MemoryManagement-linked_list_test-linked_list_test-pro-release:
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-release:
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-release:
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-release:
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
release: sub-MemoryManagement-linked_list_test-linked_list_test-pro-release sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-release sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-release sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-release

sub-MemoryManagement-linked_list_test-linked_list_test-pro-check:
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-check:
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-check:
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-check:
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
check: sub-MemoryManagement-linked_list_test-linked_list_test-pro-check sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-check sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-check sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-check

sub-MemoryManagement-linked_list_test-linked_list_test-pro-benchmark:
	@test -d MemoryManagement/linked_list_test/ || mkdir -p MemoryManagement/linked_list_test/
	cd MemoryManagement/linked_list_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/linked_list_test/linked_list_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-benchmark:
	@test -d MemoryManagement/memory_compression_test/ || mkdir -p MemoryManagement/memory_compression_test/
	cd MemoryManagement/memory_compression_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_compression_test/memory_compression_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-benchmark:
	@test -d MemoryManagement/memory_pool_test/ || mkdir -p MemoryManagement/memory_pool_test/
	cd MemoryManagement/memory_pool_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/memory_pool_test/memory_pool_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-benchmark:
	@test -d MemoryManagement/ring_buffer_test/ || mkdir -p MemoryManagement/ring_buffer_test/
	cd MemoryManagement/ring_buffer_test/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Projects/Device_t/MemoryManagement/ring_buffer_test/ring_buffer_test.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
benchmark: sub-MemoryManagement-linked_list_test-linked_list_test-pro-benchmark sub-MemoryManagement-memory_compression_test-memory_compression_test-pro-benchmark sub-MemoryManagement-memory_pool_test-memory_pool_test-pro-benchmark sub-MemoryManagement-ring_buffer_test-ring_buffer_test-pro-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

